language: c

os:
  - linux
  - osx

# only build main branch and PR's
branches:
  only:
    - main

before_script:
  - git clone --branch master --depth=1 https://github.com/asdf-vm/asdf.git asdf
  - source asdf/asdf.sh
  # workaround: asdf plugin-test assumes main branch
  - cd $TRAVIS_BUILD_DIR && git checkout -b main || echo 'Already on main'

script:
  - asdf plugin-test kind $TRAVIS_BUILD_DIR "kind version"
